---
title: "Identify Fraud from Enron Email"
author: "Tong Li"
date: "June 8, 2017"
output: html_document
---


## Question 1: 
Summarize for us the goal of this project and how machine learning is useful in trying to accomplish it. As part of your answer, give some background on the dataset and how it can be used to answer the project question. Were there any outliers in the data when you got it, and how did you handle those?  [relevant rubric items: "data exploration", "outlier investigation"]


### Answer:
The goal of this project is to find out the POI (Persons of Interest) with machine learning algorithms, using features extracted from Enron financial and email dataset. Enron Corporation was a large American energy company and went bankrupt in 2001. This large corporate bankruptcy turned out to be a big audit failure, and many senior employees were indicted, some even sentenced to prison. These senior employees who were charged with a crime or got involved in the fraud in other ways are the Persons of Interest in this project. Using proper machine learning algorithms, it is possible to identify poi from the senior employees in Enron and to know what features are most important in classifying POI and non-POI.  

The dataset used in this project contains financial and email information (20 features in total) of 144 Enron employees, with 18 POI among them. I found three outliers: 'TOTAL' and 'THE TRAVEL AGENCY IN THE PARK' which are not data of individual employee, and LOCKHART EUGENE E whose data are all missing. They were excluded from the data used in machine learning. Therefore, the final dataset used in the project contains data from 143 Enron employees.

Missing values of each feature are presented in the table as follows: 

```{r echo=FALSE, message=FALSE, warning=FALSE, results='asis'}
library(knitr)
missing <- data.frame(salary=49, deferral_payments=105, total_payments=20, loan_advances=140, bonus=62, restricted_stock_deferred=126, deferred_income=95, total_stock_value=18, expenses=49, exercised_stock_options=42, other=52, long_term_incentive=78, restricted_stock=34, director_fees=127, from_poi_to_this_person=57, from_this_person_to_poi=57, shared_receipt_with_poi=57, to_messages=57, from_messages=57, email_address=32)
table=t(missing)
kable(table, caption='No. of Missing Values for Each Feature')
```



From the table, we can see that deferral_payments, loan_advances, restricted_stock_deferred, deferred_income, long_term_incentive, director_fees have many missing values, with more than 50% are missing. These features were not used in machine learning. In addition, each individual has a distinct email_address, so email_address was also excluded from the dataset used in next steps. Therefore, 13 original features were used in machine learning algorithm.  



## Question 2: 
What features did you end up using in your POI identifier, and what selection process did you use to pick them? Did you have to do any scaling? Why or why not? As part of the assignment, you should attempt to engineer your own feature that does not come ready-made in the dataset -- explain what feature you tried to make, and the rationale behind it. (You do not necessarily have to use it in the final analysis, only engineer and test it.) In your feature selection step, if you used an algorithm like a decision tree, please also give the feature importances of the features that you use, and if you used an automated feature selection function like SelectKBest, please report the feature scores and reasons for your choice of parameter values.  [relevant rubric items: "create new features", "properly scale features", "intelligently select feature"]


### Answer:
I used 16 features in my POI identifier. There were 13 original features. The reason I selected was that they didn't contain too many missing values (as in the answer to Question 1). In addition, I created 3 new ones, i.e., 'bonus_total_ratio', 'from_email_poi_proportion', and 'to_email_poi_proportion'. The variable 'bonus_total_ratio' was created using 'bonus' divided by 'total_payments'. I expected that POI tend to have higher bonus_total_ratio compared to non-POI. The variable 'from_email_poi_proportion' was created with 'from_this_person_to_poi' divided by 'from_messages', and similarly, 'to_email_poi_proportion' was created with 'from_poi_to_this_person' divided by 'to_messages'. I expected that POI probably have more frequent contact with other POI, and their emails with other POI should take a larger proportion among all their emails.

I didn't use feature scaling for Decision Tree classifier which was my final selected algorithm, because Decision Tree does not trade-off between dimensions: it simply cut in one dimension and then move on to another. 

(But when I tried support vector machines with the data, I scaled the features with MinMaxScaler, because the kernel methods in svm are based on distance -- we want trade-off between dimensions to get the separation line that maximaizes distance. Therefore, if we do not scale the features to comparable ranges, the features with the largest range will dominate in the calculation.)

I used SelectKBest to select from the 16 features. The feature scores are as follows: salary: 15.85873091, total_payments: 8.95913665, bonus: 30.72877463, bonus_total_ratio: 13.067325, total_stock_value: 10.63385205, expenses: 4.18072148, exercised_stock_options: 9.68004143, other: 3.20445914, restricted_stock: 8.05830631, from_poi_to_this_person: 4.95866668, from_this_person_to_poi: 0.11120824, shared_receipt_with_poi: 10.72257081, to_messages: 2.616183, from_messages: 0.4353741, from_email_poi_proportion: 15.83809495, to_email_poi_proportion: 0.51923117. Among them, 12 were selected by SelectKBest algorithm. The 4 features which were not selected were from_this_person_to_poi, to_messages, from_messages, to_email_poi_proportion, whose p values were larger than 0.05.



## Question 3: 
What algorithm did you end up using? What other one(s) did you try? How did model performance differ between algorithms?  [relevant rubric item: "pick an algorithm"]


### Answer:
I ended up using Decision Tree classifier. I also tried SVM, GaussianNB, RandomForest, and Adaboost. The accuracy of these five algorithms were about 0.8 or higher, with Adaboost < Decision Tree < SVM < GaussianNB < Random Forest. Both SVM and Adaboost had very low precision and recall. Random Forest has low precision and medium recall. GaussianNB had medium score in both precision and recall. Decision Tree had high precision and medium recall. Therefore, although the accuracy looked similar, different algorithm had very different precision and recall scores. 



## Question 4: 
What does it mean to tune the parameters of an algorithm, and what can happen if you don't do this well?  How did you tune the parameters of your particular algorithm? What parameters did you tune? (Some algorithms do not have parameters that you need to tune -- if this is the case for the one you picked, identify and briefly explain how you would have done it for the model that was not your final choice or a different model that does utilize parameter tuning, e.g. a decision tree classifier).  [relevant rubric item: "tune the algorithm"]


### Answer:
To tune the parameters means to try different values of certain parameters which are used in an algorithm, in order to select the best parameter combination which can generate the best classifier. Using different values for certain parameters can dramatically change the performance of the algorithm. If it is not done well, the classifier will be more likely to make mistakes when identify POI, which makes it less powerful. 

For the final algorithm I selected which is Deicision Tree, I used GridSearchCV to tune the k value of SelectKBest to select features (=[5,6,7,8,9,10,11,12,13,14,15,16]), and the criterion (=['gini','entropy']), max_depth (=[None,1,2,3,4]), min_samples_split (=2,3,4,5), and class_weight (=[None, 'balanced']) of Decision Tree classifier.

The selected best estimators were: k=12, max_depth=2, criterion= 'entropy', min_samples_split= 2, class_weight= 'balanced'.



## Question 5: 
What is validation, and what's a classic mistake you can make if you do it wrong? How did you validate your analysis?  [relevant rubric item: "validation strategy"]


### Answer:
After the algorithm is trained, we also want to know how it preforms on some new data which is homogeneous with the train data but not exactly the same. This is because the ultimate goal of an algorithm is not to classify what we have already known as in the train set of data, but to classify or predict what we haven't known yet. Sometimes the algorithm may perform really well in train set, but it may be overfit to the train data and poor in coping with any differences. Therefore, leave part of the data out of training, and use them to validate the algorithm's ability in generalization is necessary. 

A classic mistake in validation is that if the original data is ordered in terms of any variable, and when the data is split into train and test sets without shuffling, then the data in the two sets can be very different from each other, and the algorithm tuned in the train set can never generate a good prediction in test set for the two sets are simply different things. 

I used StratifiedShuffleSplit to validate my algorithm. This validation uses stratification which rearranges the data to make sure that both train and test datasets are good representitives of the whole. This is important because this is a small dataset which is more likely to have larger variance, therefore is more likely to generate not very homogeneous train and test sets compared to a large dataset. 


## Question 6: 
Give at least 2 evaluation metrics and your average performance for each of them.  Explain an interpretation of your metrics that says something human-understandable about your algorithm's performance. [relevant rubric item: "usage of evaluation metrics"]


### Answer:
The Deicision Tree classifier gives an accuracy of 0.84, a precision of 0.60, and a recall score of 0.33. It means that for all the employees whose data were used in the machine learning algorithm, 84% of them were correctly classified as POI or non-POI, in terms of the features used in the algorithm. For all the individuals identified as POI by the algorithm, 60% are real POI (precision), and for all the POI in the real world, 33% of them are correctly identified by the algorithm.  